import Image from 'next/image';
import { locations, posts, services, site, tel, type Page } from '@/lib/content';

export function Hero({ page }: { page: Page }) {
  const acf = page.acf as { hero: { eyebrow: string; titleLine1: string; titleLine2: string; body: string; image: string; imageAlt: string; badgeTitle: string; badgeSub: string }; ticker: string[] };
  const hero = acf.hero;
  return <><section className="hero"><div className="hero-copy"><div className="sec-eye"><span className="sec-lbl">{hero.eyebrow}</span><span className="sec-rule"/></div><h1 className="hero-h1">{hero.titleLine1}<br/><em>{hero.titleLine2}</em></h1><p className="hero-body">{hero.body}</p><div className="hero-btns"><a className="btn-red" href="/contact/">Book Appointment</a><a href="/services/" className="btn-ghost">Explore Services →</a></div><div className="hero-stats"><div className="hstat"><span className="hstat-n">4.8</span><span className="hstat-l">Avg. Rating</span></div><div className="hstat"><span className="hstat-n">158</span><span className="hstat-l">Reviews</span></div><div className="hstat"><span className="hstat-n">5+</span><span className="hstat-l">Yrs Serving NKY</span></div></div></div><div className="hero-img"><Image src={hero.image} alt={hero.imageAlt} width={900} height={700} priority/><div className="hero-badge"><span className="hero-badge-dot"/><div className="hero-badge-inner"><span className="hero-badge-title">{hero.badgeTitle}</span><span className="hero-badge-sub">{hero.badgeSub}</span></div></div></div></section><div className="ticker" aria-hidden="true"><div className="ticker-inner">{[...acf.ticker, ...acf.ticker].map((item: string, index: number) => <span className="ti" key={`${item}-${index}`}>{item}</span>)}</div></div></>;
}

export function Reviews() { return <section className="reviews rv"><div className="sec-eye"><span className="sec-lbl">Reviews</span><span className="sec-rule"/></div><h2 className="sec-h2">Trusted by Northern Kentucky pet families.</h2><div className="review-grid">{['They always take time to explain what is going on and make my pet feel safe.','VMC is kind, practical, and thorough. We never feel rushed.','Both locations make veterinary care easier for our family.'].map((quote, i) => <article className="review-card" key={quote}><div className="stars">★★★★★</div><p>“{quote}”</p><strong>{['VMC Client','Dog Parent','Cat Parent'][i]}</strong></article>)}</div></section>; }

export function Why() { const cards = [['Locally owned','Decisions are made by people who live and work in this community.'],['Fear-Free handling','Low-stress techniques help visits feel calmer for pets and people.'],['Clear communication','We explain options plainly so you can make confident choices.'],['Two NKY locations','Fort Thomas and Independence make care convenient for busy families.']]; return <section className="why rv" id="why"><div className="sec-eye"><span className="sec-lbl">Why VMC</span><span className="sec-rule"/></div><h2 className="sec-h2">Veterinary care that feels personal.</h2><div className="why-grid">{cards.map(([title, desc]) => <article className="why-card" key={title}><h3>{title}</h3><p>{desc}</p></article>)}</div></section>; }

export function ServicesGrid() { return <section className="svc-outer" id="services"><div className="rv"><div className="sec-eye"><span className="sec-lbl">Veterinary Services</span><span className="sec-rule"/></div><h2 className="sec-h2">Veterinary Services for Dogs & Cats in Northern Kentucky</h2><p>From routine wellness visits to dental care, surgery, and urgent same-day appointments — our NKY vet team handles a full range of care at both locations.</p></div><div className="svc-grid rv">{services.map((service) => <article className="svc-card" key={service.slug}><div className="svc-icon">+</div><h3>{service.title}</h3><p>{service.excerpt}</p><a href={`/services/${service.slug}/`}>Learn more →</a></article>)}</div></section>; }

export function Locations() { return <section className="loc-sec rv" id="locations"><div className="sec-eye"><span className="sec-lbl">Locations</span><span className="sec-rule"/></div><h2 className="sec-h2">Two convenient Northern Kentucky veterinary clinics.</h2><div className="loc-grid">{locations.map((loc) => <article className="loc-card" key={loc.slug}><Image src={loc.image} alt={loc.imageAlt} width={720} height={420}/><div className="loc-body"><h3>{loc.title}</h3><p>{loc.acf.intro}</p><p><strong>{loc.address}</strong></p><a className="btn-red" href={tel(loc.tel)}>{loc.phone}</a><a className="btn-ghost" href={`/locations/${loc.slug}/`}>View location →</a></div></article>)}</div></section>; }

export function Team() { const staff = ['Dr. Kristi Baker — Owner & Veterinarian','Dr. Becky Golatzki — Associate Veterinarian','Cara — Office Manager','April — RVT','Jess — RVT','Taiyler — RVT']; return <section className="team-sec rv" id="team"><div className="sec-eye"><span className="sec-lbl">Team</span><span className="sec-rule"/></div><h2 className="sec-h2">People who love what they do.</h2><p>From the front desk to the treatment room, every person on the VMC team is here because they genuinely care about animals.</p><div className="staff-grid">{staff.map((member) => <div className="staff-card" key={member}><div className="staff-img"><div className="staff-img-placeholder">🐾</div></div><div className="staff-info"><div className="staff-name">{member.split(' — ')[0]}</div><div className="staff-role">{member.split(' — ')[1]}</div></div></div>)}</div></section>; }

export function NewPatients() { return <section className="npseo-outer" id="new-patients-seo"><div className="npseo-inner rv"><div className="npseo-expect"><div className="sec-eye"><span className="sec-lbl">New Patients</span><span className="sec-rule"/></div><h2 className="sec-h2">New Patient Vet Visits in Northern Kentucky</h2><p>Looking for a new veterinarian in Northern Kentucky? We welcome new patients at both Fort Thomas and Independence.</p><ul className="npseo-steps">{['Call or request an appointment at either location','Bring prior vet records or vaccination history','Arrive a few minutes early to complete paperwork','Ask about wellness plans and ongoing care options'].map((step) => <li key={step}>✓ {step}</li>)}</ul></div><div className="npseo-cta-box"><span className="npseo-cta-badge">Accepting new patients now</span><h3>Same-week appointments available at both locations.</h3><p>Whether your pet is due for a wellness exam or you just moved to the area, we make it easy to get started.</p><a href="/new-patients/" className="btn-red npseo-cta-btn">Start as a New Patient →</a></div></div></section>; }

export function BlogPreview() { return <section className="blog-preview rv"><div className="sec-eye"><span className="sec-lbl">Resources</span><span className="sec-rule"/></div><h2 className="sec-h2">Recent pet health articles.</h2><div className="post-grid">{posts.map((post) => <article className="post-card" key={post.slug}><span>{post.date}</span><h3>{post.title}</h3><p>{post.excerpt}</p><a href={`/blog/${post.slug}/`}>Read article →</a></article>)}</div></section>; }

export function ContactCards() { return <div className="contact-grid">{Object.values(site.contacts).map((loc) => <article className="contact-card" key={loc.label}><h3>{loc.label}</h3><p>{loc.address}</p><p><a href={tel(loc.tel)}>{loc.phone}</a></p><ul>{loc.hours.map((h) => <li key={h}>{h}</li>)}</ul></article>)}</div>; }
